"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ADMIN_EMAIL = exports.QR_REVIEW_BASE_URL = exports.API_URL = exports.API_BASE_URL = void 0;
const trimTrailingSlash = (value) => value.replace(/\/+$/, '');
const apiBaseFromEnv = process.env.EXPO_PUBLIC_API_BASE_URL ?? '';
const qrBaseFromEnv = process.env.EXPO_PUBLIC_QR_REVIEW_BASE_URL ?? 'https://zz-user.vercel.app';
const adminEmailFromEnv = process.env.EXPO_PUBLIC_ADMIN_EMAIL ?? 'admin@zamzam.com';
exports.API_BASE_URL = trimTrailingSlash(apiBaseFromEnv);
exports.API_URL = exports.API_BASE_URL ? `${exports.API_BASE_URL}/api` : '';
exports.QR_REVIEW_BASE_URL = trimTrailingSlash(qrBaseFromEnv);
exports.ADMIN_EMAIL = adminEmailFromEnv.trim();
